apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Graphite

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  uid: prometheus
  isDefault: true
  version: 1
  editable: true
- name: Graphite
  type: graphite
  access: proxy
  url: http://graphite:80
  uid: jp7T-f2Ik
  jsonData:
    graphiteVersion: "1.1"
